### ISSUE TITLE
Pen & Cup not displaying in Gazebo

### ISSUE THREAD

**Issue by kirantokala** [guihomework/dexterous-manipulation-tutorial#10]
Hi,

I am very new to this ROS Field. I am executing your tutorial in ROS Indigo.

When run the program, Shadow robot hand displaying in both Gazebo & Moveit.

But Pen & Cup are displaying in Moveit only.

Can you help me, What to do for Display Pen & Cup in Gazebo also?

Thanks
Sai kiran

**Comment by guihomework** [comment]
Dear @sweetsaikiran690 ,
What you request is a complex setup.
Usually the way to go is : 
* to have gazebo simulating your world, where you add objects with gazebo interface or gazebo_ros interface (spawning urdf or sdf), 
* either 1) use an object detection/recognition based on a simulated 3D sensor (laser/rgbd), and from the detected shapes fill your planning scene as I do in the tutorial (but I fake it loading existing meshes)
* or 2) load the same mesh you spawned in gazebo directly in the planning scene.

Overall there is no automatic way of having both because both software are for different purposes. The planning scene in moveit is a "representation" of the world that the robot system must build itself. 
The same goes for navigation. Obstacles in gazebo are not added automatically to a SLAM map but the SLAM map is built from the robot navigating through the gazebo world and building its own representation.

for your precise question, here is a tutorial how to create objects and spawn them in gazebo (so option 2 of the suggested work flow above)

* creating urdf (not necessarily with joints, can be single link with the mesh of the cup or the pen) http://gazebosim.org/tutorials/?tut=ros_urdf
* spawning them http://gazebosim.org/tutorials?tut=ros_roslaunch&cat=connect_ros section spawn urdf
