### ISSUE TITLE
Attached body 'pen' not found issue

### ISSUE THREAD

**Issue by sweetsaikiran690** [guihomework/dexterous-manipulation-tutorial#9]
Hello,

I don't have too much experience using MoveIt, so maybe I'm missing something obvious but I can't see it. I'm using a shadow hand arm configuration with ROS indigo, I'm basically following the tutorial and trying to adapt the code to this particular case.

When I try to "pick" a pen

[ INFO] [1501407512.378839491, 46.625000000]: No planner specified. Using default.
[ INFO] [1501407512.379128506, 46.625000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1501407512.414876133, 46.640000000]: RRTConnect: Created 7 states (5 start + 2 goal)
[ INFO] [1501407512.414948040, 46.640000000]: Solution found in 0.036033 seconds
[ INFO] [1501407512.475997863, 46.669000000]: SimpleSetup: Path simplification took 0.060942 seconds and changed from 6 to 17 states
[ INFO] [1501407512.479136059, 46.671000000]: Planning adapters have added states at index positions: [ 0 ]
[ WARN] [1501407512.494942117, 46.677000000]: Dropping first 1 trajectory point(s) out of 69, as they occur before the current time.
First valid point will be reached in 0.110s.
[ WARN] [1501407512.496331426, 46.677000000]: Dropping first 1 trajectory point(s) out of 69, as they occur before the current time.
First valid point will be reached in 0.110s.
[ERROR] [1501407523.346083702, 51.606000000]: Attached body 'pen' not found
[ INFO] [1501407523.346756963, 51.606000000]: Planning attempt 1 of at most 1
[ERROR] [1501407523.347155265, 51.606000000]: No end-effector specified for pick action
[ INFO] [1501407736.210904186, 155.226000000]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1501407736.212212864, 155.226000000]: No optimization objective specified, defaulting to PathLengthOptimizationObjective
[ INFO] [1501407736.212318472, 155.226000000]: Planner configuration 'right_arm[RRTConnectkConfigDefault]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1501407736.212697577, 155.226000000]: right_arm[RRTConnectkConfigDefault]: Starting planning with 1 states already in datastructure
[ INFO] [1501407736.258364861, 155.243000000]: right_arm[RRTConnectkConfigDefault]: Created 4 states (2 start + 2 goal)
[ INFO] [1501407736.258427573, 155.243000000]: Solution found in 0.046003 seconds
[ INFO] [1501407736.258485758, 155.243000000]: SimpleSetup: Path simplification took 0.000009 seconds and changed from 3 to 2 states

**Comment by guihomework** [comment]
This tutorial is not maintained for indigo anymore but I must admit might be failing with latest kinetic too.
Please first provide some info:
* Do you see the pen after the planning scene is filled ? as 
![pen](https://raw.githubusercontent.com/wiki/guihomework/dexterous-manipulation-tutorial/media/images/tuto-using/planning-env-objects.png)
* Which step exactly did you reach ?

**Comment by guihomework** [comment]
The first error message ```Attached body 'pen' not found ``` is not a problem, I added a note in the wiki.

The second error is the problem.
Do you see such messages when starting the move_group.launch ?
```
[ WARN] [1502292320.789420790]: Could not identify parent group for end-effector 'right_arm_and_hand_ee'
[ WARN] [1502292320.789458780]: Could not identify parent group for end-effector 'right_arm_and_manipulator_ee'
[ WARN] [1502292320.789471493]: Could not identify parent group for end-effector 'right_arm_and_wrist_ee'
```
it seems the end_effector are not correctly "attached" to the parent group, and this produces the error
you saw : 
```[ERROR] [1501407523.347155265, 51.606000000]: No end-effector specified for pick action```

I will see how to circumvent that. 
Stay tuned

**Comment by guihomework** [comment]
I fixed the tutorial.
* The pen is 1cm higher (to avoid some collision)
* The arm goes to an intermediate pose now (end of part1 of tutorial 2) because apparently from straight-up there is more change the planner fails to reach pre-grasp pose.
* The grasps.yaml was fixed to take into account the new ur10 to shadow hand mounting (rotated) and to use new prefixed joint names

Please update to the shadow_kinetic branch of the tutorial (or re-apply the latest changes to your clone without applying changes relative to kinetic version of moveit)

Another fix is necessary until the Shadow Robot Team fixes this on their side :

* Fix the sr_multi_moveit package to get a valid end-effector using [this](https://github.com/guihomework/dexterous-manipulation-tutorial/blob/shadow_kinetic/srdfFix.patch) patch

The tutorial 2 part 2 worked for me on kinetic now.

**Comment by kirantokala** [comment]
I am able to see Pen & Cup after running the program.

Still at the end of Tutorial2 Part1, It is working fine.

But from Tutorial2 Part2 it is not working for me.


ret = arm.pick("pen",[four_finger_grasp])

This line is not working.

**Comment by sweetsaikiran690** [comment]
Please help me to solve this issue.

**Comment by kirantokala** [comment]
I tried with Updated package. But Still same problem.

When I run the grasp_app.py program, it is showing error like

[ WARN] [1502355354.983148102]: Fail: ABORTED: Must specify group in motion plan request

In Main Robot hand Launch program

[ INFO] [1502355309.505567825]: Constructing new MoveGroup connection for group 'right_arm' in namespace ''
[ INFO] [1502355310.439762536]: TrajectoryExecution will use old service capability.
[ INFO] [1502355310.439829828]: Ready to take MoveGroup commands for group right_arm.
[ INFO] [1502355310.439864986]: Looking around: no
[ INFO] [1502355310.439895991]: Replanning: no
[ WARN] [1502355351.887264756]: MessageFilter [target=/world ]: Discarding message from [/moveit_grasp_app_24305_1502355350694] due to empty frame_id.  This message will only print once.
[ERROR] [1502355354.966144599]: Attached body 'pen' not found
[ INFO] [1502355354.982381599]: Planning attempt 1 of at most 1
[ERROR] [1502355354.982608168]: No end-effector specified for pick action

**Comment by kirantokala** [comment]
Please help me to solve this issue. I am very new to this. Just I am following this tutorial as it is and I am learning.

**Comment by guihomework** [comment]
Did you apply the fix in sr_multi_moveit ? This is also required to fix the 
```[ERROR] [1502355354.982608168]: No end-effector specified for pick action```

**Comment by kirantokala** [comment]
Yes. I applied the fix in sr_multi_moveit .

But still showing this error.

[ERROR] [1502355354.982608168]: No end-effector specified for pick action

**Comment by kirantokala** [comment]
This is my total code.


#!/usr/bin/env python

import sys
import rospy
import rospkg, genpy
import yaml
import copy

from moveit_commander import RobotCommander, PlanningSceneInterface, MoveGroupCommander
from moveit_commander import roscpp_initialize, roscpp_shutdown
from moveit_msgs.msg import RobotState, Grasp
from geometry_msgs.msg import PoseStamped

def load_grasps():
    grasp_yaml = yaml.load(open(resourcepath+'grasps/grasps.yaml'))
    grasps={}
    for g in grasp_yaml:
        grasp = Grasp()
        genpy.message.fill_message_args(grasp, g)
          
        if grasp.id is None or grasp.id == "":
            raise Exception("Grasp has no id")
        else:
            grasps[grasp.id] = grasp
    return grasps

if __name__ == "__main__":
    roscpp_initialize(sys.argv)
    rospy.init_node('moveit_grasp_app', anonymous=True)
    rospy.loginfo("Starting grasp app")
    # add some code here

    scene = PlanningSceneInterface()
    rospy.sleep(1)

    scene.remove_world_object("ground")
    scene.remove_world_object("cup")
    scene.remove_world_object("pen")
    rospy.sleep(1)

    p = PoseStamped()
    p.header.frame_id = "world"
    p.pose.position.x = 0
    p.pose.position.y = 0
    p.pose.position.z = -0.05
    p.pose.orientation.x = 0
    p.pose.orientation.y = 0
    p.pose.orientation.z = 0
    p.pose.orientation.w = 1

    scene.add_box("ground", p, (3, 3, 0.02))

    rospack = rospkg.RosPack()
    resourcepath = rospack.get_path('robot_project')+"/resources/"

    p.pose.position.x = 0.7
    p.pose.position.y = 0.7
    p.pose.position.z = 0.0
    scene.add_mesh("cup",p,resourcepath+'objects/cup.dae')

    p.pose.position.x = 0.72
    p.pose.position.z = 0.05
    scene.add_mesh("pen",p,resourcepath+'objects/pen.dae')


    robot = RobotCommander()
    print "Available groups: ",robot.get_group_names()

    arm = MoveGroupCommander("right_arm")
    arm.set_start_state_to_current_state()
    arm.set_planner_id("RRTConnectConfigDefault") 
    arm.set_planning_time(5.0)

    arm.set_named_target("ra_up")
  
    motionplan = arm.plan()

    arm.execute(motionplan)
    rospy.sleep(1)

    hand = MoveGroupCommander("right_hand")
    hand.set_start_state_to_current_state()
    hand.set_planner_id("LBKPIECEkConfigDefault") 
    hand.set_planning_time(10.0)
    hand.set_named_target("pack")
    hand.go()

    
    grasps = load_grasps()
    four_finger_grasp = grasps['four_finger_precision_horizontal']

    four_finger_grasp.grasp_pose.header.frame_id = "pen"
    four_finger_grasp.pre_grasp_approach.direction.header.frame_id = "pen"
    four_finger_grasp.post_grasp_retreat.direction.header.frame_id = "pen"
    four_finger_grasp.post_place_retreat.direction.header.frame_id = "pen"

    arm.detach_object("pen")

    ret = arm.pick("pen",[four_finger_grasp])

    two_finger_grasp = grasps['two_finger_precision_horizontal']
    two_finger_grasp.grasp_pose.header.frame_id = "pen"
    two_finger_grasp.pre_grasp_approach.direction.header.frame_id = "pen"
    two_finger_grasp.post_grasp_retreat.direction.header.frame_id = "pen"
    two_finger_grasp.post_place_retreat.direction.header.frame_id = "pen"

    rospy.spin()
    roscpp_shutdown()
    rospy.loginfo("Stopping grasp app")

**Comment by kirantokala** [comment]
Can you tell me, anything wrong in this?

**Comment by guihomework** [comment]
Hi, 
I fixed the tutorial 2 part 1  (pen needs to be at 0.06 on z to not touch the cup)
```
p.pose.position.z = 0.06
scene.add_mesh("pen",p,resourcepath+'objects/pen.dae')
```
and also the hand should be open (not pack), otherwise there are collision.
```
hand.set_named_target("open")
```

I see at least one missing line in your program
```
ret = arm.pick("pen",[two_finger_grasp])
```
To be safe, comment out the other line once you see how it fails (this is a progressive tutorial so things are meant to be activated once to see things happen, and deactivated later on)
```
# ret = arm.pick("pen",[four_finger_grasp])
```

but these is not your main problem you currently see (but would have come later)

please check the generated srdf to see if the end-effector is really well defined :  
```
  rosparam get /robot_description_semantic -p | grep ra_moveit_ee
```
you should see this after you applied the patch
```
379:    <end_effector group="right_hand" name="ra_moveit_ee" parent_link="ra_ee_link"/>
```

if not then rebuild all (are you working from devel or install folder ?), and try again. If the srdf is not right, the patch is not correctly applied somehow or not taken into account.

**Comment by kirantokala** [comment]
Thanks for your reply. 

Now that error is not coming. But Motion also not coming


[33m[ WARN] [1502362047.337213068, 22.309000000]: MessageFilter [target=/world ]: Discarding message from [/moveit_grasp_app_17682_1502362042052] due to empty frame_id.  This message will only print once.[0m
[0m[ INFO] [1502362054.049060880, 23.625000000]: Planning request received for MoveGroup action. Forwarding to planning pipeline.[0m
[33m[ WARN] [1502362054.056258387, 23.626000000]: Cannot find planning configuration for group 'right_arm' using planner 'RRTConnectConfigDefault'. Will use defaults instead.[0m
[0m[ INFO] [1502362054.059194780, 23.627000000]: No optimization objective specified, defaulting to PathLengthOptimizationObjective[0m
[0m[ INFO] [1502362054.059422758, 23.627000000]: No planner specified. Using default.[0m
[0m[ INFO] [1502362054.060275992, 23.627000000]: RRTConnect: Starting planning with 1 states already in datastructure[0m
[0m[ INFO] [1502362054.102896569, 23.633000000]: RRTConnect: Created 4 states (2 start + 2 goal)[0m
[0m[ INFO] [1502362054.103108978, 23.633000000]: Solution found in 0.043225 seconds[0m
[0m[ INFO] [1502362054.115772584, 23.636000000]: SimpleSetup: Path simplification took 0.012214 seconds and changed from 3 to 2 states[0m
[0m[ INFO] [1502362054.124576362, 23.637000000]: Received new trajectory execution service request...[0m
[0m[ INFO] [1502362058.625836350, 25.438000000]: Execution completed: SUCCEEDED[0m
[0m[ INFO] [1502362059.363423787, 25.739000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.[0m
[0m[ INFO] [1502362059.363580468, 25.739000000]: Planning attempt 1 of at most 1[0m
[0m[ INFO] [1502362059.363720392, 25.739000000]: Starting state is just outside bounds (joint 'rh_MFJ3'). Assuming within bounds.[0m
[0m[ INFO] [1502362059.363737837, 25.739000000]: Starting state is just outside bounds (joint 'rh_THJ2'). Assuming within bounds.[0m
[33m[ WARN] [1502362059.364418064, 25.739000000]: Cannot find planning configuration for group 'right_hand' using planner 'LBKPIECEkConfigDefault'. Will use defaults instead.[0m
[0m[ INFO] [1502362059.364906216, 25.739000000]: No planner specified. Using default.[0m
[0m[ INFO] [1502362059.365256761, 25.739000000]: RRTConnect: Starting planning with 1 states already in datastructure[0m
[0m[ INFO] [1502362059.388727980, 25.751000000]: RRTConnect: Created 5 states (2 start + 3 goal)[0m
[0m[ INFO] [1502362059.388816397, 25.751000000]: Solution found in 0.023825 seconds[0m
[0m[ INFO] [1502362059.393059049, 25.753000000]: SimpleSetup: Path simplification took 0.004149 seconds and changed from 4 to 2 states[0m
[0m[ INFO] [1502362059.396481330, 25.755000000]: Planning adapters have added states at index positions: [ 0 ][0m
[0m[ INFO] [1502362066.724910775, 28.895000000]: Planning attempt 1 of at most 1[0m
[0m[ INFO] [1502362066.797261206, 28.921000000]: Added plan for pipeline 'pick'. Queue is now of size 1[0m
[0m[ INFO] [1502362067.409917562, 29.107000000]: Attaching world object 'pen' to link 'ra_ee_link'[0m
[0m[ INFO] [1502362067.410207006, 29.107000000]: Attached object 'pen' to link 'ra_ee_link'[0m
[0m[ INFO] [1502362067.780926138, 29.200000000]: Manipulation plan 0 failed at stage 'approach & translate' on thread 0[0m
[33m[ WARN] [1502362067.781422948, 29.200000000]: All supplied grasps failed. Retrying last grasp in verbose mode.[0m
[0m[ INFO] [1502362067.781562012, 29.200000000]: Re-added last failed plan for pipeline 'pick'. Queue is now of size 1[0m
[0m[ INFO] [1502362067.833633530, 29.218000000]: Orientation constraint satisfied for link 'ra_ee_link'. Quaternion desired: 0.500000 0.500000 0.500000 0.500000, quaternion actual: 0.505316 0.495576 0.499463 0.499596, error: x=0.001881, y=0.009863, z=0.009616, tolerance: x=0.010000, y=0.010000, z=0.010000[0m
[0m[ INFO] [1502362067.833689904, 29.218000000]: Position constraint satisfied on link 'ra_ee_link'. Desired: 0.820000, 0.360000, 0.070000, current: 0.819588, 0.360011, 0.070180[0m
[0m[ INFO] [1502362067.833706214, 29.218000000]: Differences 0.0004

**Comment by kirantokala** [comment]
When run grasp_app.py file

**Comment by kirantokala** [comment]
[33m[ WARN] [1502362053.182187257, 23.456000000]: No lambda on param server, using 0.010000 as default
Available groups:  ['rh_fingers', 'rh_first_finger', 'rh_little_finger', 'rh_middle_finger', 'rh_ring_finger', 'rh_thumb', 'rh_wrist', 'right_arm', 'right_arm_and_hand', 'right_arm_and_wrist', 'right_hand']
[0m[ INFO] [1502362054.045665758, 23.624000000]: TrajectoryExecution will use old service capability.
[0m[ INFO] [1502362054.045883867, 23.624000000]: Ready to take MoveGroup commands for group right_arm.
[0m[ INFO] [1502362059.362789821, 25.738000000]: TrajectoryExecution will use old service capability.
[0m[ INFO] [1502362059.362850221, 25.739000000]: Ready to take MoveGroup commands for group right_hand.
[33m[ WARN] [1502362069.159649749, 29.618000000]: Fail: ABORTED: No motion plan found. No execution attempted.

**Comment by guihomework** [comment]
Are you using fake controllers in move_it or real controllers also moving the arm in gazebo ? (this is a different controller manager setting). 
Sometimes real/simulated controllers cannot reach desired position well, but here it apparently says no errors, just that the position and orientation contraints were satisfied. If it found no plan, then I don't really know what is happening. 
Can you at all plan in moveit, using rviz manual motion plan request, set the goal close to the grasping pose of the pen using the interactive markers and see if you can get a plan and an execution to there.
If this works, than either there are incompatibilities between kinetic/indigo or some files are not exactly what I have. 
It works for me with your app.

**Comment by kirantokala** [comment]
Actually, Now it is executing without error. 
But, After executed this line
ret = arm.pick("pen",[two_finger_grasp])

Hand is going to that pen. But not picking the pen.

Do you know the reason?

**Comment by guihomework** [comment]
There should be a message like : 
```
[ INFO] [1502359303.534014119]: Found a contact between 'cup' (type 'Object') and 'pen' (type 'Robot attached'), which constitutes a collision. Contact information is not stored.
```
if the pen is touching when lifting after being attached to the robot.

I had this before fixing the pen position a little higher (it was touching the bottom of the cup)

**Comment by kirantokala** [comment]
Sorry, This message is not coming. What to do?

**Comment by kirantokala** [comment]
If you have no problem, Can you tell me your mobile number, I will call you.

**Comment by guihomework** [comment]
Dear @sweetsaikiran690 , 
I am really sorry you cannot make this tutorial work on your own, after my fixes. As said, indigo is not supported anymore.
I am also not available for support over phone.
I will now close this specific issue.
If you think there is another issue with kinetic, open a new one.

**Comment by guihomework** [comment]
@sweetsaikiran690 , after working with Shadow Robot team to fix the srdf, I re-run the tutorial which then did not pick up the pen as you had. And after a full re-run it did not approach the pen either.
But I had clear errors like
```
[ INFO] [1502956075.492301567]: Found a contact between 'ground' (type 'Object') and 'ra_upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
```
which comes from the iksolver providing a pose of the arm that penetrates in the table and hence fails. This does not come from the tutorial, this problem comes from moveit/planners not managing to find a plan with a redundant arm. Randomness and planner settings are crucial.

You can try tune the settings of the planners, select another planner, add more retries, to make the plan work. 
I will add a note on that in the tutorial, but I have few chances on fixing that for every environment this tutorial runs in. Across ROS versions, moveit/planners might have slight changes in their behavior.
